#!/bin/bash
# =============================================================================
# Netdata Webhook Configuration for Fenrir Bot
# =============================================================================
# This script helps configure Netdata to send alerts to the Fenrir bot.
#
# Usage: ./setup-netdata-webhook.sh <FENRIR_WEBHOOK_URL> [WEBHOOK_SECRET]
#
# Example:
#   ./setup-netdata-webhook.sh http://192.168.1.100:8080
#   ./setup-netdata-webhook.sh http://192.168.1.100:8080 my_secret_token
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  🐺 Netdata → Fenrir Bot Webhook Configuration${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_header

# Check arguments
if [ -z "$1" ]; then
    echo "Usage: $0 <FENRIR_WEBHOOK_URL> [WEBHOOK_SECRET]"
    echo
    echo "Examples:"
    echo "  $0 http://192.168.1.100:8080"
    echo "  $0 http://fenrir-bot.local:8080 my_secret_token"
    echo
    exit 1
fi

WEBHOOK_URL="$1"
WEBHOOK_SECRET="${2:-}"

# Netdata config paths
NETDATA_CONFIG_DIR="/etc/netdata"
HEALTH_ALARM_NOTIFY="${NETDATA_CONFIG_DIR}/health_alarm_notify.conf"

# Check if Netdata is installed
if ! command -v netdata &> /dev/null; then
    print_error "Netdata is not installed on this system"
    echo "Install Netdata first: https://www.netdata.cloud/get-started/"
    exit 1
fi

print_success "Netdata found"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_warning "Not running as root. May need sudo for config changes."
fi

# Check if config directory exists
if [ ! -d "$NETDATA_CONFIG_DIR" ]; then
    print_error "Netdata config directory not found at $NETDATA_CONFIG_DIR"
    exit 1
fi

print_info "Configuring webhook at: ${WEBHOOK_URL}/webhook/netdata"
echo

# Create or update the health_alarm_notify.conf
CONFIG_CONTENT="# =============================================================================
# Fenrir Bot Webhook Configuration
# Generated by setup-netdata-webhook.sh
# =============================================================================

# Enable webhook notifications
SEND_CUSTOM=\"YES\"

# Fenrir Bot webhook URL
DEFAULT_RECIPIENT_CUSTOM=\"${WEBHOOK_URL}/webhook/netdata\"

# Webhook method and format
custom_sender() {
    local WEBHOOK_URL=\"\${1}\"
    local HOST=\"\${2}\"
    local UNIQUE_ID=\"\${3}\"
    local ALARM_ID=\"\${4}\"
    local EVENT_ID=\"\${5}\"
    local WHEN=\"\${6}\"
    local NAME=\"\${7}\"
    local CHART=\"\${8}\"
    local STATUS=\"\${9}\"
    local OLD_STATUS=\"\${10}\"
    local VALUE=\"\${11}\"
    local OLD_VALUE=\"\${12}\"
    local SRC=\"\${13}\"
    local DURATION=\"\${14}\"
    local NON_CLEAR_DURATION=\"\${15}\"
    local UNITS=\"\${16}\"
    local INFO=\"\${17}\"
    local VALUE_STRING=\"\${18}\"
    local OLD_VALUE_STRING=\"\${19}\"
    local IMAGE=\"\${20}\"
    local TOTAL_WARNINGS=\"\${21}\"
    local TOTAL_CRITICAL=\"\${22}\"
    local ALARM_LOG=\"\${23}\"
    local FAMILY=\"\${24}\"
    
    # Build JSON payload for Fenrir
    local JSON_PAYLOAD
    JSON_PAYLOAD=\$(cat <<EOF
{
    \"host\": \"\${HOST}\",
    \"unique_id\": \${UNIQUE_ID:-0},
    \"alarm_id\": \${ALARM_ID:-0},
    \"event_id\": \${EVENT_ID:-0},
    \"name\": \"\${NAME}\",
    \"chart\": \"\${CHART}\",
    \"family\": \"\${FAMILY}\",
    \"status\": \"\${STATUS}\",
    \"old_status\": \"\${OLD_STATUS}\",
    \"value\": \${VALUE:-0},
    \"old_value\": \${OLD_VALUE:-0},
    \"units\": \"\${UNITS}\",
    \"info\": \"\${INFO}\",
    \"duration\": \${DURATION:-0},
    \"non_clear_duration\": \${NON_CLEAR_DURATION:-0},
    \"when\": \${WHEN:-0},
    \"value_string\": \"\${VALUE_STRING}\",
    \"old_value_string\": \"\${OLD_VALUE_STRING}\",
    \"total_warnings\": \${TOTAL_WARNINGS:-0},
    \"total_critical\": \${TOTAL_CRITICAL:-0}
}
EOF
)

    # Headers
    local HEADERS=\"Content-Type: application/json\"
$([ -n "$WEBHOOK_SECRET" ] && echo "    HEADERS=\"\${HEADERS} -H 'Authorization: Bearer ${WEBHOOK_SECRET}'\"")

    # Send the webhook
    httpcode=\$(curl -s -o /dev/null -w '%{http_code}' \\
        -X POST \\
        -H \"Content-Type: application/json\" \\
        $([ -n "$WEBHOOK_SECRET" ] && echo "-H \"Authorization: Bearer ${WEBHOOK_SECRET}\" \\")
        --connect-timeout 5 \\
        --max-time 10 \\
        -d \"\${JSON_PAYLOAD}\" \\
        \"\${WEBHOOK_URL}\" 2>/dev/null)
    
    if [ \"\${httpcode}\" = \"200\" ]; then
        return 0
    else
        return 1
    fi
}
"

# Backup existing config if it exists
if [ -f "$HEALTH_ALARM_NOTIFY" ]; then
    BACKUP_FILE="${HEALTH_ALARM_NOTIFY}.backup.$(date +%Y%m%d_%H%M%S)"
    print_info "Backing up existing config to: $BACKUP_FILE"
    sudo cp "$HEALTH_ALARM_NOTIFY" "$BACKUP_FILE" 2>/dev/null || cp "$HEALTH_ALARM_NOTIFY" "$BACKUP_FILE"
fi

# Write new config
print_info "Writing webhook configuration..."
echo "$CONFIG_CONTENT" | sudo tee "$HEALTH_ALARM_NOTIFY" > /dev/null 2>/dev/null || echo "$CONFIG_CONTENT" > "$HEALTH_ALARM_NOTIFY"

print_success "Configuration written to $HEALTH_ALARM_NOTIFY"

# Test the webhook
echo
print_info "Testing webhook connection..."
TEST_PAYLOAD='{
    "host": "test-host",
    "unique_id": 1,
    "alarm_id": 1,
    "event_id": 1,
    "name": "test_alert",
    "chart": "system.cpu",
    "family": "cpu",
    "status": "WARNING",
    "old_status": "CLEAR",
    "value": 75.5,
    "old_value": 50.0,
    "units": "%",
    "info": "Test alert from setup script",
    "duration": 60,
    "non_clear_duration": 60,
    "when": '$(date +%s)'
}'

HEADERS="-H \"Content-Type: application/json\""
if [ -n "$WEBHOOK_SECRET" ]; then
    HEADERS="$HEADERS -H \"Authorization: Bearer $WEBHOOK_SECRET\""
fi

HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' \
    -X POST \
    -H "Content-Type: application/json" \
    ${WEBHOOK_SECRET:+-H "Authorization: Bearer $WEBHOOK_SECRET"} \
    --connect-timeout 5 \
    --max-time 10 \
    -d "$TEST_PAYLOAD" \
    "${WEBHOOK_URL}/webhook/netdata" 2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "200" ]; then
    print_success "Webhook test successful! Check your Discord channel for a test alert."
elif [ "$HTTP_CODE" = "401" ]; then
    print_error "Webhook returned 401 Unauthorized. Check your WEBHOOK_SECRET."
elif [ "$HTTP_CODE" = "000" ]; then
    print_warning "Could not connect to webhook. Make sure Fenrir bot is running."
    print_info "You can test manually later with:"
    echo "  curl -X POST -H 'Content-Type: application/json' \\"
    echo "    -d '{\"host\":\"test\",\"status\":\"WARNING\",\"name\":\"test\",\"value\":50,\"units\":\"%\"}' \\"
    echo "    ${WEBHOOK_URL}/webhook/netdata"
else
    print_warning "Webhook returned HTTP $HTTP_CODE"
fi

# Restart Netdata
echo
print_info "Restarting Netdata to apply changes..."
if sudo systemctl restart netdata 2>/dev/null; then
    print_success "Netdata restarted successfully"
elif sudo service netdata restart 2>/dev/null; then
    print_success "Netdata restarted successfully"
else
    print_warning "Could not restart Netdata automatically. Please restart manually:"
    echo "  sudo systemctl restart netdata"
fi

echo
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Configuration Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo
echo "Next steps:"
echo "  1. Make sure Fenrir bot is running with WEBHOOK_ENABLED=true"
echo "  2. Netdata will now send alerts to: ${WEBHOOK_URL}/webhook/netdata"
echo "  3. Configure which alerts to send in /etc/netdata/health.d/"
echo
echo "Useful Netdata alert commands:"
echo "  - View active alarms: netdatacli alarms"
echo "  - Trigger test alert: netdatacli test-alert"
echo "  - Edit alert config: sudo nano /etc/netdata/health.d/cpu.conf"
echo
